William Craig
MFG598
HW5


1) Create one random integer array, aVec, containing 20 values ranging from 0 to 100. 
Generate a random float value, b, between 0 and 100. Find the index in aVec whose value is 
closest to b. Print also the value within aVec through the index.
Example 
A = [46, 76, 74, 27, 6, 74, 53, 63, 86, 7, 77, 17, 72, 16, 61, 77, 25, 67, 18, 34]
b = 90.07
Index of A closest to b = 8
A[8] = 86

In [22]:
import numpy as np
aVec = np.random.randint(0, 101, 20)
print(f"The list of random integers is:\n{aVec}")

b = np.random.uniform(0, 100)
print(f"The randomly generated float value is: {b}")

index = np.abs(aVec - b).argmin()

print(f"The index of aVec closest in value to b is: {index}")
print(f"The value of that index is:{aVec[index]}")

The list of random integers is:
[30 77 38 38 61 20 54 79 80 15 93 42 54 81 56 48  5 13 54 47]
The randomly generated float value is: 62.136736729736185
The index of aVec closest in value to b is: 4
The value of that index is:61


2) Write a Python program to create random vector with values between 0 and 1 of size 15 
and replace the maximum value within it by -1.

In [72]:
#random.rand inherently generates a uiform distribution of values between 0 and 1. 
    #The intention is that the output can then be scaled.
vector = np.random.rand(15)

print(vector)

vector_modified = vector
print("\n")

vector_modified[vector.argmax()] = -1

print(vector_modified)


[0.59733814 0.68592409 0.2384287  0.01302637 0.49367324 0.95954996
 0.15568184 0.86374785 0.10368143 0.09060836 0.79884522 0.99513588
 0.20849828 0.5014978  0.80148725]


[ 0.59733814  0.68592409  0.2384287   0.01302637  0.49367324  0.95954996
  0.15568184  0.86374785  0.10368143  0.09060836  0.79884522 -1.
  0.20849828  0.5014978   0.80148725]


3) Write a Python script to extract a set of numbers between a given range (between 10 and 
20, both inclusive). The given list can be a=[22,1,4, 32, 12, 5, 16, 10, 19, 20]

In [65]:
a=[22,1,4, 32, 12, 5, 16, 10, 19, 20]
#numpy solution:
import numpy as np
a_rray = np.array(a)

result = a_rray[(a_rray >= 10) & (a_rray <= 20)]

print(result)


[12 16 10 19 20]


In [66]:
#conventional solution
a_extracted = []
for item in a:
    if item <= 20:
        if item >=10:
            a_extracted.append(item)
print(a_extracted)



# print(a[(a >= 10) & (a <= 20)]) doesn't work... Not supported between instances of list and int


[12, 16, 10, 19, 20]


4) Replace all the positions at which non-zeros exist in the given matrix, A to -1. The given 2D 
array is 
A = [1 0 1 0 1 1 1 0 1 0 0
        0 1 0 1 1 0 1 0 1 1 1
        0 0 0 0 0 0 0 0 1 1 1]

In [79]:
#Can't seem to get the provided array to work due to the lack of delimiting. If it's a string, there are no ""
A = np.array([1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
              0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
              0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1])

print(A)

A[A != 0] = -1

print(A)

[1 0 1 0 1 1 1 0 1 0 0 0 1 0 1 1 0 1 0 1 1 1 0 0 0 0 0 0 0 0 1 1 1]
[-1  0 -1  0 -1 -1 -1  0 -1  0  0  0 -1  0 -1 -1  0 -1  0 -1 -1 -1  0  0
  0  0  0  0  0  0 -1 -1 -1]


5) Write a numpy program that creates a 1D vector with random integer values ranging from 
10 to 100 with 20 elements. Further, for each value that is below the mean of all the values 
in the vector, replace those values with 0.

In [104]:
import numpy as np

A = np.random.randint(10, 101, size = 20)

print(f"Original array: \n{A}\n")

print(f"Mean of the original array: {A.mean()}\n")
A[A <= A.mean()] = 0

print(f"Original array with all values below mean replaced:\n{A}")

Original array: 
[36 55 16 28 95 98 20 40 89 17 33 71 38 82 74 41 63 26 46 10]

Mean of the original array: 48.9

Original array with all values below mean replaced:
[ 0 55  0  0 95 98  0  0 89  0  0 71  0 82 74  0 63  0  0  0]


6) Consider an elementary system of three linear equations: x + 2y + z = 2, 2x + 6y + z = 7, x + y 
+ 4z = 3, Solve for x, y and z using a python program using the numpy library.

In [110]:
#Need to consider in terms of matrices
import numpy as np
A = np.array([(1, 2, 1),(2, 6, 1),(1, 1, 4)])
b = np.array([2, 7, 3])

A_solved = np.linalg.solve(A, b)

print(A_solved)

[-3.  2.  1.]


7) Randomly  generate  two  objects.  The  first  object  is  a  1D  array,  a  vector  ‘v’  of  10  integer 
elements. Randomly generate a second 2D array, B, a matrix of 10 x 5 elements. Subtract the 
1d array, ‘v’ from the 2d matrix B, such that each item of v subtracts from respective column 
of  A.  The  resulting  matrix  must  still  be  of  shape  10  x  5.  The  values  in  the  vector  randomly 
range from (1, 100).

In [4]:
import numpy as np
object_one = np.random.randint(0, 101, size = 10)
object_two  = np.random.rand(10, 5)
print(object_one)
print(object_two)

result = object_two - object_one.reshape(10, 1)

print(result)

[99 47 89 37 55 82 97  2 84 60]
[[0.31816503 0.97252889 0.87649969 0.77709006 0.98494582]
 [0.21525512 0.19733179 0.99306333 0.32841249 0.17733431]
 [0.72476896 0.150997   0.17269374 0.6053656  0.89693914]
 [0.47921755 0.84550422 0.34224506 0.91124793 0.79698776]
 [0.42022722 0.63591514 0.80429091 0.91453032 0.00516168]
 [0.2152671  0.8008461  0.81094627 0.62975101 0.64149098]
 [0.32159803 0.60661987 0.31779802 0.63821242 0.04046962]
 [0.99275308 0.26083413 0.38319645 0.66530373 0.90256863]
 [0.02239355 0.04024586 0.59244947 0.43078307 0.98892948]
 [0.83543291 0.10733475 0.47880508 0.86759273 0.83600551]]
[[-98.68183497 -98.02747111 -98.12350031 -98.22290994 -98.01505418]
 [-46.78474488 -46.80266821 -46.00693667 -46.67158751 -46.82266569]
 [-88.27523104 -88.849003   -88.82730626 -88.3946344  -88.10306086]
 [-36.52078245 -36.15449578 -36.65775494 -36.08875207 -36.20301224]
 [-54.57977278 -54.36408486 -54.19570909 -54.08546968 -54.99483832]
 [-81.7847329  -81.1991539  -81.18905373 -81.37

8) Read the numData.data file using the genfromtxt() method available from numpy. Normalize 
the values within this dataset, with each value to be between 0 and 1. Normalization should 
occur across row-by-row operation.

In [2]:
import numpy as np
#Inspected data in notepad to find the delimiter per visual inspection
data = np.genfromtxt("numData.data", delimiter=",")


#Special operations are required in order to ignore nan in the original dataset, like using np.nanmean or np.nanmedian.
#Because we are normalizing the data, we will simply need to discard the last column.
nan_cols = np.isnan(data).any(axis=0)
#The use of .any allows us to scan the column as we move along the first row.

data_nan_subtracted = data[:, ~nan_cols]



#Normalization here involves subtracting the smallest value, then dividing it by the 'range' of the data. 
#We use axis = 1 to make this a row-wise operation. Thus, it is row-by-row.
# data_normalized = (data - data.min(axis=1, keepdims=True)) / (data.max(axis=1, keepdims=True) - data.min(axis=1, keepdims=True))

#The use of keepdims = True preserves the dimensions of the original array. The code can't function otherwise.
data_normalized = (data_nan_subtracted - data_nan_subtracted.min(axis=1, keepdims=True)) / (data_nan_subtracted.max(axis=1, keepdims=True) - data_nan_subtracted.min(axis=1, keepdims=True))


print("Original data:\n", data[:5])
print("Normalized data:\n", data_normalized[:5])



Original data:
 [[5.1 3.5 1.4 0.2 nan]
 [4.9 3.  1.4 0.2 nan]
 [4.7 3.2 1.3 0.2 nan]
 [4.6 3.1 1.5 0.2 nan]
 [5.  3.6 1.4 0.2 nan]]
Normalized data:
 [[1.         0.67346939 0.24489796 0.        ]
 [1.         0.59574468 0.25531915 0.        ]
 [1.         0.66666667 0.24444444 0.        ]
 [1.         0.65909091 0.29545455 0.        ]
 [1.         0.70833333 0.25       0.        ]]


9) Read the numData.data file. Filter the rows in such a way that the 3rd column > 2.0 and the 
first column is <5.0.

In [13]:
import numpy as np

# Loading data from the file again here.
data = np.genfromtxt("numData.data", delimiter=",")


#Original file for comparison:
print("5-row head of original data:\n", data[:5])

#After this data is filtered, we should expect a very small number of rows that meet our criteria.
#We're going to apply a boolean mask that simply masks out any rows that do not meet the expected values.
#When we place brackets after the 'data', we assign conditions to it. We can require multiple conditions with &.
filtered_data = data[(data[:, 0] < 5.0) & (data[:, 2] > 2.0)]


print("Filtered data:\n", filtered_data)

5-row head of original data:
 [[5.1 3.5 1.4 0.2 nan]
 [4.9 3.  1.4 0.2 nan]
 [4.7 3.2 1.3 0.2 nan]
 [4.6 3.1 1.5 0.2 nan]
 [5.  3.6 1.4 0.2 nan]]
Filtered data:
 [[4.9 2.4 3.3 1.  nan]
 [4.9 2.5 4.5 1.7 nan]]


10) Given 3 arrays of equal size, write a short numpy script that finds the maximum value across 
each of the three arrays at each index position of the array. Store these values in a single 
array. 
Example
A = [9, 10, 7, 2, 4, 1, 0]
B = [10, 8, 0, 5, 8, 3, 1]
C = [8, 9, 9, 8, 3, 2, 9]
Result = [10, 10, 9, 8, 8, 3, 9]

In [4]:
import numpy as np

# Define the three arrays
A = np.array([9, 10, 7, 2, 4, 1, 0])
B = np.array([10, 8, 0, 5, 8, 3, 1])
C = np.array([8, 9, 9, 8, 3, 2, 9])

#This is a nested statement. np automatically iterates through the array left to right.
    #First, we find the maximum between rows A and B. This could be done with A and C, or B and C as well.
    #Then, we treat the maximum of those two values as a single row. We compare it with C, and add it to the result.
result = np.maximum(np.maximum(A, B), C)

# Print the result
print(result)

[10 10  9  8  8  3  9]
