HOMEWORK 6
(This HW covers Numpy)
(A single Jupyter Notebook (.ipynb) or (.py) to be submitted to Canvas. Do not zip the files before 
submission. All of the solutions below must use the numpy package )


1) Create one random integer array, aVec, containing 20 values ranging from 0 to 100. 
Generate a random float value, b, between 0 and 100. Find the index in aVec whose value is 
closest to b. Print also the value within aVec through the index.
Example 
A = [46, 76, 74, 27, 6, 74, 53, 63, 86, 7, 77, 17, 72, 16, 61, 77, 25, 67, 18, 34]
b = 90.07
Index of A closest to b = 8
A[8] = 86

In [22]:
import numpy as np
aVec = np.random.randint(0, 101, 20)
print(f"The list of random integers is:\n{aVec}")

b = np.random.uniform(0, 100)
print(f"The randomly generated float value is: {b}")

index = np.abs(aVec - b).argmin()

print(f"The index of aVec closest in value to b is: {index}")
print(f"The value of that index is:{aVec[index]}")

The list of random integers is:
[30 77 38 38 61 20 54 79 80 15 93 42 54 81 56 48  5 13 54 47]
The randomly generated float value is: 62.136736729736185
The index of aVec closest in value to b is: 4
The value of that index is:61


2) Write a Python program to create random vector with values between 0 and 1 of size 15 
and replace the maximum value within it by -1.

In [72]:
#random.rand inherently generates a uiform distribution of values between 0 and 1. 
    #The intention is that the output can then be scaled.
vector = np.random.rand(15)

print(vector)

vector_modified = vector
print("\n")

vector_modified[vector.argmax()] = -1

print(vector_modified)


[0.59733814 0.68592409 0.2384287  0.01302637 0.49367324 0.95954996
 0.15568184 0.86374785 0.10368143 0.09060836 0.79884522 0.99513588
 0.20849828 0.5014978  0.80148725]


[ 0.59733814  0.68592409  0.2384287   0.01302637  0.49367324  0.95954996
  0.15568184  0.86374785  0.10368143  0.09060836  0.79884522 -1.
  0.20849828  0.5014978   0.80148725]


3) Write a Python script to extract a set of numbers between a given range (between 10 and 
20, both inclusive). The given list can be a=[22,1,4, 32, 12, 5, 16, 10, 19, 20]

In [65]:
a=[22,1,4, 32, 12, 5, 16, 10, 19, 20]
#numpy solution:
import numpy as np
a_rray = np.array(a)

result = a_rray[(a_rray >= 10) & (a_rray <= 20)]

print(result)


[12 16 10 19 20]


In [66]:
#conventional solution
a_extracted = []
for item in a:
    if item <= 20:
        if item >=10:
            a_extracted.append(item)
print(a_extracted)



# print(a[(a >= 10) & (a <= 20)]) doesn't work... Not supported between instances of list and int


[12, 16, 10, 19, 20]


4) Replace all the positions at which non-zeros exist in the given matrix, A to -1. The given 2D 
array is 
A = [1 0 1 0 1 1 1 0 1 0 0
        0 1 0 1 1 0 1 0 1 1 1
        0 0 0 0 0 0 0 0 1 1 1]

In [79]:
#Can't seem to get the provided array to work due to the lack of delimiting. If it's a string, there are no ""
A = np.array([1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
              0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
              0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1])

print(A)

A[A != 0] = -1

print(A)

[1 0 1 0 1 1 1 0 1 0 0 0 1 0 1 1 0 1 0 1 1 1 0 0 0 0 0 0 0 0 1 1 1]
[-1  0 -1  0 -1 -1 -1  0 -1  0  0  0 -1  0 -1 -1  0 -1  0 -1 -1 -1  0  0
  0  0  0  0  0  0 -1 -1 -1]


5) Write a numpy program that creates a 1D vector with random integer values ranging from 
10 to 100 with 20 elements. Further, for each value that is below the mean of all the values 
in the vector, replace those values with 0.

In [104]:
import numpy as np

A = np.random.randint(10, 101, size = 20)

print(f"Original array: \n{A}\n")

print(f"Mean of the original array: {A.mean()}\n")
A[A <= A.mean()] = 0

print(f"Original array with all values below mean replaced:\n{A}") 


Original array: 
[36 55 16 28 95 98 20 40 89 17 33 71 38 82 74 41 63 26 46 10]

Mean of the original array: 48.9

Original array with all values below mean replaced:
[ 0 55  0  0 95 98  0  0 89  0  0 71  0 82 74  0 63  0  0  0]


6) Consider an elementary system of three linear equations: x + 2y + z = 2, 2x + 6y + z = 7, x + y 
+ 4z = 3, Solve for x, y and z using a python program using the numpy library.

In [110]:
#Need to consider in terms of matrices
import numpy as np
A = np.array([(1, 2, 1),(2, 6, 1),(1, 1, 4)])
b = np.array([2, 7, 3])

A_solved = np.linalg.solve(A, b)

print(A_solved)

[-3.  2.  1.]


7) Randomly  generate  two  objects.  The  first  object  is  a  1D  array,  a  vector  ‘v’  of  10  integer 
elements. Randomly generate a second 2D array, B, a matrix of 10 x 5 elements. Subtract the 
1d array, ‘v’ from the 2d matrix B, such that each item of v subtracts from respective column 
of  A.  The  resulting  matrix  must  still  be  of  shape  10  x  5.  The  values  in  the  vector  randomly 
range from (1, 100).

In [122]:
import numpy as np
object_one = np.random.randint(0, 101, size = 10)
object_2  = np.random.rand(10, 5)
print(object_one)
print(object_2)



[72 63 59 63 17 86 19 59 67 61]
[[0.01500704 0.70558072 0.65787137 0.26861279 0.03768788]
 [0.93223149 0.99385733 0.07506847 0.01421186 0.02521063]
 [0.45015893 0.97548596 0.45813001 0.18280813 0.80202088]
 [0.11749284 0.65999717 0.15299588 0.97195162 0.61088382]
 [0.4603044  0.05125792 0.83460217 0.18230099 0.53940831]
 [0.40187101 0.27661445 0.45427699 0.59969222 0.82189489]
 [0.49932479 0.4011447  0.6095388  0.26159797 0.22103647]
 [0.84091447 0.43181812 0.67266312 0.91233312 0.59680039]
 [0.41482749 0.97404923 0.79961623 0.0037897  0.05852566]
 [0.20885829 0.68662822 0.77116924 0.95917023 0.53423437]]


8) Read the numData.data file using the genfromtxt() method available from numpy. Normalize 
the values within this dataset, with each value to be between 0 and 1. Normalization should 
occur across row-by-row operation.

9) Read the numData.data file. Filter the rows in such a way that the 3rd column > 2.0 and the 
first column is <5.0.

10) Given 3 arrays of equal size, write a short numpy script that finds the maximum value across 
each of the three arrays at each index position of the array. Store these values in a single 
array. 
Example
A = [9, 10, 7, 2, 4, 1, 0]
B = [10, 8, 0, 5, 8, 3, 1]
C = [8, 9, 9, 8, 3, 2, 9]
Result = [10, 10, 9, 8, 8, 3, 9]