HW5
HW6
P7
P9
P10
P11

#Start with HW5

In [11]:
#Create a,random,integer,array,aVec,containing 20 vals
import numpy as np
aVec = np.random.randint(0, 101, size = 20)
print(aVec)

randfloat = np.random.uniform(0, 100)

print(randfloat)

[94  3 10 71 20  8  6  1 77 74 80 97  1 75  6 55 97 42 81  6]
70.89304437734434


In [26]:
#Create a random vector with values between 0 and 1 of size 15
#Replace max value with -1

#vector has 3 values, so array of 3

#can't be integers

vector = np.random.uniform(0, 1, size = 15)
print(vector)

new_vector = vector.copy()

new_vector_max_index = new_vector.argmax()

new_vector[new_vector_max_index] = -1

print(new_vector)



[0.12871475 0.04453114 0.46246177 0.46152179 0.8285867  0.5914373
 0.06581922 0.35224335 0.11134085 0.78236176 0.53539802 0.9018846
 0.6995534  0.7455292  0.54856902]
[ 0.12871475  0.04453114  0.46246177  0.46152179  0.8285867   0.5914373
  0.06581922  0.35224335  0.11134085  0.78236176  0.53539802 -1.
  0.6995534   0.7455292   0.54856902]


In [29]:
#Write a python script to extract a set of numbers between a range
#Given list is:
a = [22,1,4, 32, 12, 5, 16, 10, 19, 20]
#Need to extract anything between 10 and 20, inclusive

a_ray = np.array(a)

extracted = a_ray[(a_ray >= 10) & (a_ray <= 20)]

print(extracted)

[12 16 10 19 20]


In [40]:
#Repalce all positions at which non-zeros exist in given matrix A to -1
#so... IF A[i] != 0: 
        # A[i] = new_val

A = np.array([1,0,1,0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1])

A = np.where(A !=0, -1, A)

print(A)

#Can use a boolean mask for this or np.where

[-1  0 -1  0 -1 -1 -1  0 -1  0  0  0 -1  0 -1 -1  0 -1  0 -1 -1 -1  0  0
  0  0  0  0  0  0 -1 -1 -1]


In [42]:
#Another way to solve the above

A = np.array([1,0,1,0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1])

non_zero_indices = A != 0

A[non_zero_indices] = -1

print(A)

[-1  0 -1  0 -1 -1 -1  0 -1  0  0  0 -1  0 -1 -1  0 -1  0 -1 -1 -1  0  0
  0  0  0  0  0  0 -1 -1 -1]


In [49]:
# Consider system of three linear equations
# x+2y + z = 2
#2x + 6y + z = 7
#x + y + 4z = 3
#Solve!

#This is an augmented matrix, but we need two matrices for numpy.
A = np.array([[1, 2, 1, 2],
             [2, 6, 1, 7],
             [1, 1, 4, 3]])

B = A[:, :-1]
b = A[:, -1]


solution = np.linalg.solve(B, b)

print(solution)

[-3.  2.  1.]


In [60]:
#Generate a 1D array with 10 integer elements
v = np.random.randint(1, 101, size = 10)
#randomly generate a 2D array B matrix of 10x5
B = np.random.randint(0,101, size = (10,5))

#Now subtract each item of v from its respective column of B

result = B-v[:, np.newaxis]

print(f"{B}\n\n")
print(f"{v}\n\n")
print(result)



[[ 42  88  60   5  85]
 [ 39  23  80  72  27]
 [ 88  23  78 100  89]
 [  2  66   7  95   7]
 [ 71  84  27  79  39]
 [ 77   0  43  20  10]
 [ 97  13  77  77  90]
 [ 71  24  66  81  54]
 [ 45  51  92  23  86]
 [ 75  83  45  61  16]]


[ 67  19  39  72  38  63  90 100  14  25]


[[-25  21  -7 -62  18]
 [ 20   4  61  53   8]
 [ 49 -16  39  61  50]
 [-70  -6 -65  23 -65]
 [ 33  46 -11  41   1]
 [ 14 -63 -20 -43 -53]
 [  7 -77 -13 -13   0]
 [-29 -76 -34 -19 -46]
 [ 31  37  78   9  72]
 [ 50  58  20  36  -9]]


In [109]:
#Now read the numData.data file using genfromtxt

data = np.genfromtxt('../homework/numData.data', delimiter = ',')

print(data[:10])

data.dtype

data.shape

[[5.1 3.5 1.4 0.2 nan]
 [4.9 3.  1.4 0.2 nan]
 [4.7 3.2 1.3 0.2 nan]
 [4.6 3.1 1.5 0.2 nan]
 [5.  3.6 1.4 0.2 nan]
 [5.4 3.9 1.7 0.4 nan]
 [4.6 3.4 1.4 0.3 nan]
 [5.  3.4 1.5 0.2 nan]
 [4.4 2.9 1.4 0.2 nan]
 [4.9 3.1 1.5 0.1 nan]]


(150, 5)

In [113]:
filtered_data = data[:,:4]

In [116]:
normalized_data = (filtered_data-filtered_data.min())/((filtered_data.max())-(filtered_data.min()))

print(normalized_data[:100])

[[0.64102564 0.43589744 0.16666667 0.01282051]
 [0.61538462 0.37179487 0.16666667 0.01282051]
 [0.58974359 0.3974359  0.15384615 0.01282051]
 [0.57692308 0.38461538 0.17948718 0.01282051]
 [0.62820513 0.44871795 0.16666667 0.01282051]
 [0.67948718 0.48717949 0.20512821 0.03846154]
 [0.57692308 0.42307692 0.16666667 0.02564103]
 [0.62820513 0.42307692 0.17948718 0.01282051]
 [0.55128205 0.35897436 0.16666667 0.01282051]
 [0.61538462 0.38461538 0.17948718 0.        ]
 [0.67948718 0.46153846 0.17948718 0.01282051]
 [0.6025641  0.42307692 0.19230769 0.01282051]
 [0.6025641  0.37179487 0.16666667 0.        ]
 [0.53846154 0.37179487 0.12820513 0.        ]
 [0.73076923 0.5        0.14102564 0.01282051]
 [0.71794872 0.55128205 0.17948718 0.03846154]
 [0.67948718 0.48717949 0.15384615 0.03846154]
 [0.64102564 0.43589744 0.16666667 0.02564103]
 [0.71794872 0.47435897 0.20512821 0.02564103]
 [0.64102564 0.47435897 0.17948718 0.02564103]
 [0.67948718 0.42307692 0.20512821 0.01282051]
 [0.64102564 

In [124]:
# Read the numData.data file. Filter the rows in such a way that the 3rd column > 2.0 and the
# first column is <5.0.

#advanced indexing syntax applied here.
#First conditional 
first_and_third = data[(data[:, 0] < 5.0) & (data[:, 2] > 2.0)]

print(first_and_third)

[[4.9 2.4 3.3 1.  nan]
 [4.9 2.5 4.5 1.7 nan]]


Given 3 arrays of equal size, write a short numpy script that finds the maximum value across
each of the three arrays at each index position of the array. Store these values in a single
array.

Example

A = [9, 10, 7, 2, 4, 1, 0]

B = [10, 8, 0, 5, 8, 3, 1]

C = [8, 9, 9, 8, 3, 2, 9]

Result = [10, 10, 9, 8, 8, 3, 9]


In [127]:
A = [9, 10, 7, 2, 4, 1, 0]

B = [10, 8, 0, 5, 8, 3, 1]

C = [8, 9, 9, 8, 3, 2, 9]

max_vals = np.maximum.reduce([A,B,C])

print(max_vals)

[10 10  9  8  8  3  9]


In [135]:
#find best least squares fit of data
#in form of straight line y = mx + c
#using numpy
import pandas as pd

data = {
    'Advertising Expenditure': [12, 14, 17, 21, 26, 30],
    'Profit': [60, 70, 90, 100, 100, 120]
}

dataframe = pd.DataFrame(data)

dataframe

#Let's say I want row names instead.



Advertising Expenditure  Profit
0                       12      60
1                       14      70
2                       17      90
3                       21     100
4                       26     100
5                       30     120

In [136]:
dataframe_horizontal = pd.DataFrame.from_dict(data, orient = 'index') #can name columns here, columns = ['a', 'b']

dataframe_horizontal

0   1   2    3    4    5
Advertising Expenditure  12  14  17   21   26   30
Profit                   60  70  90  100  100  120

In [142]:
#Best least squares...

coefficients = np.polyfit(dataframe['Advertising Expenditure'], dataframe['Profit'], deg = 1)

print(f'y = {coefficients[0]} * x + {coefficients[1]}')

y = 2.9674796747967487 * x + 30.650406504065003
